### ISSUE TITLE
Atom is repeating $ prefix when autocomplete variables.

### ISSUE THREAD

**Issue by juanfernandoe** [hhvm/atom-ide-hack#1]
Hi,

When you are writing a variable name and then choose an autocompletion option
it repeats the $ prefix.

For example, if you write $cro and autocompletion suggest to you $cron_mapper 
and you pick the option the result is $$cron_mapper.

**Comment by fredemmott** [comment]
This is basically https://github.com/atom/atom-languageclient/issues/220 - atom-languageclient needs support for textedit-based completion.
