### ISSUE TITLE
Atom don't automatically start hh_client

### ISSUE THREAD

**Issue by juanfernandoe** [hhvm/atom-ide-hack#2]
Hi,

When you open a project in Atom, the expected is atom starts automatically hh_client inside
the active project but it doesn't happen, you have to start hh_client in the terminal inside the 
desired project.

**Comment by fredemmott** [comment]
This needs to be filed against https://github.com/atom/atom-languageclient - though as far as I'm aware, neither atom-IDE itself or atom-languageclient are maintained now. I suggest looking at Visual Studio Code instead.
